import type { IFactureRF } from './responsable-financier-columns';

export interface IHistoriqueStatut {
  label: string;
  date?: string;
  agent?: string;
  montant?: number;
  isCurrent?: boolean;
  isPending?: boolean;
}

export interface IFactureRFDetail extends IFactureRF {
  historique: IHistoriqueStatut[];
}

export const MOCK_FACTURES: IFactureRFDetail[] = [
  {
    id: '1',
    numero: 'FAC-2026-0212',
    partenaire: 'SOCIBE SARL',
    montant: 4500000,
    montantRecouvre: 4500000,
    pourcentageRecouvre: 100,
    cycle: 'Mensuel',
    emission: '02-05-2026',
    depotPartenaire: { date: '03-05-2026', agent: 'M. KOUAME' },
    depotBanque: '06-05-2026',
    agent: 'K. Medard',
    statut: 'Soldé',
    historique: [
      { label: 'Facture émise', date: '02-05-2026', agent: 'K. Medard' },
      { label: 'En attente de validation' },
      { label: 'Validée par le Responsable Financier', agent: 'KONE YACOUBA' },
      { label: 'Recouvrement lancé', agent: 'K. Medard' },
      { label: 'Déposée chez le partenaire', date: '03-05-2026', agent: 'K. Medard' },
      { label: 'Preuve de dépôt ajoutée', agent: 'K. Medard' },
      { label: 'Visa DG apposé', agent: 'DG' },
      { label: 'Soldée — paiement reçu', date: '06-05-2026', montant: 4500000, isCurrent: true },
    ],
  },
  {
    id: '2',
    numero: 'FAC-2026-0213',
    partenaire: 'Groupe AFRIDIS',
    montant: 8750000,
    montantRecouvre: 5250000,
    pourcentageRecouvre: 60,
    cycle: 'Bihebdomadaire',
    emission: '04-05-2026',
    depotPartenaire: { date: '05-05-2026', agent: 'Mme DIARRA' },
    depotBanque: null,
    agent: 'K. Medard',
    statut: 'Acompte 1',
    historique: [
      { label: 'Facture émise', date: '04-05-2026', agent: 'K. Medard' },
      { label: 'En attente de validation' },
      { label: 'Validée par le Responsable Financier', agent: 'KONE YACOUBA' },
      { label: 'Recouvrement lancé', agent: 'K. Medard' },
      { label: 'Déposée chez le partenaire', date: '05-05-2026', agent: 'K. Medard' },
      { label: 'Preuve de dépôt ajoutée', agent: 'K. Medard', isCurrent: true },
      { label: 'Visa DG apposé', agent: 'DG', isPending: true },
      { label: 'Soldée — paiement reçu', montant: 5250000, isPending: true },
    ],
  },
  {
    id: '3',
    numero: 'FAC-2026-0214',
    partenaire: 'SIVOA Industries',
    montant: 2100000,
    montantRecouvre: null,
    pourcentageRecouvre: null,
    cycle: 'Hebdomadaire',
    emission: '05-05-2026',
    depotPartenaire: { date: '06-05-2026', agent: 'M. TRAORE' },
    depotBanque: null,
    agent: 'S. Kouadio',
    statut: 'Déposé partenaire',
    historique: [
      { label: 'Facture émise', date: '05-05-2026', agent: 'S. Kouadio' },
      { label: 'En attente de validation' },
      { label: 'Validée par le Responsable Financier', agent: 'KONE YACOUBA' },
      { label: 'Recouvrement lancé', agent: 'S. Kouadio' },
      { label: 'Déposée chez le partenaire', date: '06-05-2026', agent: 'M. TRAORE', isCurrent: true },
    ],
  },
  {
    id: '4',
    numero: 'FAC-2026-0215',
    partenaire: 'BATIMAT CI',
    montant: 12000000,
    montantRecouvre: null,
    pourcentageRecouvre: null,
    cycle: 'Mensuel',
    emission: '06-05-2026',
    depotPartenaire: null,
    depotBanque: null,
    agent: 'S. Kouadio',
    statut: 'Recouvrement',
    historique: [
      { label: 'Facture émise', date: '06-05-2026', agent: 'S. Kouadio' },
      { label: 'En attente de validation' },
      { label: 'Validée par le Responsable Financier', agent: 'KONE YACOUBA' },
      { label: 'Recouvrement lancé', agent: 'S. Kouadio', isCurrent: true },
    ],
  },
  {
    id: '5',
    numero: 'FAC-2026-0216',
    partenaire: 'Pharma Express',
    montant: 1350000,
    montantRecouvre: null,
    pourcentageRecouvre: null,
    cycle: 'Journalier',
    emission: '—',
    depotPartenaire: null,
    depotBanque: null,
    agent: '—',
    statut: 'Validé',
    historique: [
      { label: 'Facture émise', agent: '—' },
      { label: 'En attente de validation' },
      { label: 'Validée par le Responsable Financier', agent: 'KONE YACOUBA', isCurrent: true },
    ],
  },
  {
    id: '6',
    numero: 'FAC-2026-0217',
    partenaire: 'Cocoa Trading',
    montant: 6800000,
    montantRecouvre: 6800000,
    pourcentageRecouvre: 100,
    cycle: 'Mensuel',
    emission: '01-05-2026',
    depotPartenaire: { date: '02-05-2026', agent: 'M. KONE' },
    depotBanque: null,
    agent: 'A. Yao',
    statut: 'Preuve ajoutée',
    historique: [
      { label: 'Facture émise', date: '01-05-2026', agent: 'A. Yao' },
      { label: 'En attente de validation' },
      { label: 'Validée par le Responsable Financier', agent: 'KONE YACOUBA' },
      { label: 'Recouvrement lancé', agent: 'A. Yao' },
      { label: 'Déposée chez le partenaire', date: '02-05-2026', agent: 'M. KONE' },
      { label: 'Preuve de dépôt ajoutée', agent: 'A. Yao', isCurrent: true },
    ],
  },
  {
    id: '7',
    numero: 'FAC-2026-0218',
    partenaire: 'Yopougon Logistics',
    montant: 980000,
    montantRecouvre: null,
    pourcentageRecouvre: null,
    cycle: 'Hebdomadaire',
    emission: '—',
    depotPartenaire: null,
    depotBanque: null,
    agent: '—',
    statut: 'À valider',
    historique: [
      { label: 'Facture émise', agent: '—' },
      { label: 'En attente de validation', isCurrent: true },
    ],
  },
  {
    id: '8',
    numero: 'FAC-2026-0219',
    partenaire: 'Sucrivoire',
    montant: 15500000,
    montantRecouvre: 9300000,
    pourcentageRecouvre: 60,
    cycle: 'Mensuel',
    emission: '03-05-2026',
    depotPartenaire: { date: '04-05-2026', agent: 'Mme COULIBALY' },
    depotBanque: null,
    agent: 'K. Medard',
    statut: 'Visé DGA',
    historique: [
      { label: 'Facture émise', date: '03-05-2026', agent: 'K. Medard' },
      { label: 'En attente de validation' },
      { label: 'Validée par le Responsable Financier', agent: 'KONE YACOUBA' },
      { label: 'Recouvrement lancé', agent: 'K. Medard' },
      { label: 'Déposée chez le partenaire', date: '04-05-2026', agent: 'Mme COULIBALY' },
      { label: 'Preuve de dépôt ajoutée', agent: 'K. Medard' },
      { label: 'Visa DG apposé', agent: 'DG', isCurrent: true },
    ],
  },
  {
    id: '9',
    numero: 'FAC-2026-0220',
    partenaire: "Côte d'Ivoire Telecom",
    montant: 3200000,
    montantRecouvre: 1050000,
    pourcentageRecouvre: 33,
    cycle: 'Bihebdomadaire',
    emission: '07-05-2026',
    depotPartenaire: { date: '08-05-2026', agent: 'M. BAMBA' },
    depotBanque: null,
    agent: 'A. Yao',
    statut: 'Acompte 1',
    historique: [
      { label: 'Facture émise', date: '07-05-2026', agent: 'A. Yao' },
      { label: 'En attente de validation' },
      { label: 'Validée par le Responsable Financier', agent: 'KONE YACOUBA' },
      { label: 'Recouvrement lancé', agent: 'A. Yao' },
      { label: 'Déposée chez le partenaire', date: '08-05-2026', agent: 'M. BAMBA' },
      { label: 'Acompte reçu — 1 050 000 F CFA (33%)', date: '10-05-2026', montant: 1050000, isCurrent: true },
    ],
  },
  {
    id: '10',
    numero: 'FAC-2026-0221',
    partenaire: 'Abidjan Catering',
    montant: 540000,
    montantRecouvre: 540000,
    pourcentageRecouvre: 100,
    cycle: 'Hebdomadaire',
    emission: '29-04-2026',
    depotPartenaire: { date: '30-04-2026', agent: 'M. SORO' },
    depotBanque: '02-05-2026',
    agent: 'S. Kouadio',
    statut: 'Soldé',
    historique: [
      { label: 'Facture émise', date: '29-04-2026', agent: 'S. Kouadio' },
      { label: 'En attente de validation' },
      { label: 'Validée par le Responsable Financier', agent: 'KONE YACOUBA' },
      { label: 'Recouvrement lancé', agent: 'S. Kouadio' },
      { label: 'Déposée chez le partenaire', date: '30-04-2026', agent: 'M. SORO' },
      { label: 'Preuve de dépôt ajoutée', agent: 'S. Kouadio' },
      { label: 'Visa DG apposé', agent: 'DG' },
      { label: 'Soldée — paiement reçu', date: '02-05-2026', montant: 540000, isCurrent: true },
    ],
  },
];
