name: Deploy to Production

on:
  push:
    branches: [ "Yamoussa" ]
    paths-ignore:
      - ".idea"
      - "**/*.md"
      - ".github/**"
      - "README.md"
      - "docs/**"

concurrency:
  group: "deploy-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  notify_start:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord - Start
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"username\": \"CI/CD Bot\",
            \"embeds\": [{
              \"title\": \"🚀 Workflow Started\",
              \"description\": \"\
                👤 Pushed by: ${{ github.actor }}\n\
                🌿 Branch: ${{ github.ref_name }}\n\
                📝 Commit: ${{ github.event.head_commit.message }}\n\
                🔗 Repo: https://github.com/${{ github.repository }}\n\
                ⚙️ Job: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\
                \",
                \"color\": 16776960
              } ]
              }" \
              ${{ secrets.DISCORD_WEBHOOK }}
  


  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2   # ou v1 si tu préfères, mais v2 est plus récent

      # 1. Cache du global cache de Bun (téléchargements des packages)
      - name: Cache Bun global install cache
        uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-global-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun-global-

      # 2. Cache du node_modules local (optionnel mais très efficace avec Bun)
      - name: Cache node_modules
        uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-node-modules-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun-node-modules-

      - name: Install dependencies
        run: bun install --frozen-lockfile   # --frozen-lockfile = sécurité CI

      - name: Type check
        run: bun x tsc --noEmit --pretty

  build:
    needs: typecheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: docker/setup-buildx-action@v4

      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        run: echo "VERSION=ci-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set lowercase image name
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ env.VERSION }}
            NEXT_PUBLIC_BACKEND_PROTOCOL=${{ secrets.NEXT_PUBLIC_BACKEND_PROTOCOL }}
            NEXT_PUBLIC_API_ERP_URL=${{ secrets.NEXT_PUBLIC_API_ERP_URL }}
            NEXT_PUBLIC_API_RESTO_URL=${{ secrets.NEXT_PUBLIC_API_RESTO_URL }}
            NEXT_PUBLIC_API_CLIENT_URL=${{ secrets.NEXT_PUBLIC_API_CLIENT_URL }}
            NEXT_PUBLIC_API_DELIVERY_URL=${{ secrets.NEXT_PUBLIC_API_DELIVERY_URL }}
            NEXT_PUBLIC_API_BACKEND_URL=${{ secrets.NEXT_PUBLIC_API_BACKEND_URL }}
            NEXT_PUBLIC_API_SOCKET_URL=${{ secrets.NEXT_PUBLIC_API_SOCKET_URL }}
            NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy
        run: |
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          
            IMAGE="$IMAGE_NAME:latest"
          
            echo "Pull latest image..."
            docker pull \$IMAGE
          
            echo "Stopping old container..."
            docker stop turbo-erp-front || true
            docker rm turbo-erp-front || true
          
            echo "Starting new container..."
            docker run -d \
              --name turbo-erp-front \
              --restart unless-stopped \
              --memory "300m" \
              --cpus="1.0" \
              --env-file /var/www/turbo/prod/turbo-delivery-erp/.env \
              -p 4002:3000 \
              \$IMAGE
          
            echo "Cleaning unused images..."
            docker image prune -f
          
            echo "Deployment done."
          
          EOF
  notify_end:
    needs: [ build, deploy ]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Set status
        run: |
          if [ "${{ needs.build.result }}" != "success" ] || [ "${{ needs.deploy.result }}" != "success" ]; then
            echo "COLOR=15548997" >> $GITHUB_ENV
            echo "TITLE=❌ Workflow Failed" >> $GITHUB_ENV
          else
            echo "COLOR=5763719" >> $GITHUB_ENV
            echo "TITLE=✅ Workflow Successful" >> $GITHUB_ENV
          fi

      - name: Notify Discord - Result
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"username\": \"CI/CD Bot\",
            \"embeds\": [{
              \"title\": \"${{ env.TITLE }}\",
              \"description\": \"\
              👤 Pushed by: ${{ github.actor }}\n\
              🌿 Branch: ${{ github.ref_name }}\n\
              📝 Commit: ${{ github.event.head_commit.message }}\n\
              🔗 Repo: https://github.com/${{ github.repository }}\n\
              ⚙️ Job: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\
              \",
              \"color\": ${{ env.COLOR }}
            } ]
            }" \
            ${{ secrets.DISCORD_WEBHOOK }}